# vercel-merge.yml
name: Deploy to Vercel on Merge

on:
  push:
    branches:
      - main  # Trigger on any push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the repository

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20  # Use the Vercel GitHub Action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel authentication token
          github-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub authentication token
          vercel-args: '--prod'  # Deploy to production
          vercel-org-id: ${{ secrets.ORG_ID }}  # Vercel Organization ID
          vercel-project-id: ${{ secrets.PROJECT_ID }}  # Vercel Project ID
          
      - name: Comment on successful deployment
        if: success()  # Only run this if the previous step was successful
        run: |
          echo "Deployment to Vercel was successful!" | gh pr comment ${{ github.event.pull_request.number }} --body "$(cat)"
          # This will comment on the pull request with a success message. Ensure PR exists.
