name: Deploy to Vercel on PR

on:
  pull_request:
    branches:
      - main  # Trigger for PRs targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel for Preview
        uses: amondnet/vercel-action@v20
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
        
      - name: Set preview URL output
        run: |
          echo "preview-url=${{ steps.vercel-deploy.outputs.preview-url }}" >> $GITHUB_OUTPUT
        
      - name: Output Preview URL
        run: |
          echo "Preview URL: ${{ steps.vercel-deploy.outputs.preview-url }}"

      - name: Comment on PR with Preview URL
        if: success() && github.event.pull_request # Only comment if it's a PR
        run: |
          preview_url="${{ steps.vercel-deploy.outputs.preview-url }}"
          if [ -n "$preview_url" ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "Here is your preview URL: $preview_url"
          fi
